export const WAPLAT_B2B_WEBVIEW = "WAPLAT_B2B_WEBVIEW";
export const WAPLAT_CHECK_WEBVIEW = "WAPLAT_CHECK_WEBVIEW";
export const WAPLAT_B2B_ADMIN = "WAPLAT_B2B_ADMIN";
export const DEBUNK_ADMIN = "DEBUNK_ADMIN";
export const DEBUNK_WECHAT = "DEBUNK_WECHAT";
export const WEBSITES = "WEBSITES";
